name: Update and Obfuscate Worker 

on: 
  schedule: 
    - cron: '0 8 * * *'   # 每天08:00 UTC运行 
  workflow_dispatch:      # 允许手动触发

permissions: 
  contents: write

jobs: 
  update-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 安装依赖
        run: | 
          npm install -g javascript-obfuscator
          sudo apt-get update && sudo apt-get install -y jq curl unzip

      - name: 获取最新 release tag
        id: get_release
        run: | 
          latest_tag=$(curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest | jq -r '.tag_name')
          echo "最新版本: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: 读取当前版本号并判断是否更新
        id: check_version
        run: |
          if [ -f "version.txt" ]; then 
            current_version=$(cat version.txt | tr -d '\n' | tr -d '\r')
          else 
            current_version=""
          fi
          echo "当前版本: $current_version"
          
          if [ "$current_version" != "$latest_tag" ]; then
            echo "需要更新"
            curl -L -o origin.js "https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/download/${{ env.latest_tag }}/worker.js"
            
            # 混淆 JS 代码
            javascript-obfuscator origin.js --output _worker.js \
              --compact true \
              --identifier-names-generator hexadecimal \
              --rename-globals false \
              --string-array false \
              --transform-object-keys false \
              --self-defending false \
              --simplify true

            # 添加伪变更，确保 Git 能识别为更新
            echo "// Auto obfuscated at $(date -u)" >> _worker.js

            # 更新 version.txt
            echo "${{ env.latest_tag }}" > version.txt
          else
            echo "无需更新"
          fi

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔁 Obfuscate _worker.js (version: ${{ env.latest_tag }})"
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
